insert into jkr_koodistot.osapuolenrooli(id, selite) values
    (1,'Omistaja'),
    (2,'Vanhin asukas'),
    (11,'Tilaaja sekajäte'),
    (12,'Tilaaja biojäte'),
    (13,'Tilaaja muovipakkaus'),
    (14,'Tilaaja kartonkipakkaus'),
    (15,'Tilaaja lasipakkaus'),
    (16,'Tilaaja metalli'),
    (17,'Tilaaja monilokero'),
    (18,'Tilaaja liete'),
    (19,'Tilaaja aluekeräyspiste'),
    (111,'Kimppaisäntä sekajäte'),
    (112,'Kimppaisäntä biojäte'),
    (113,'Kimppaisäntä muovipakkaus'),
    (114,'Kimppaisäntä kartonkipakkaus'),
    (115,'Kimppaisäntä lasipakkaus'),
    (116,'Kimppaisäntä metalli'),
    (117,'Kimppaisäntä monilokero'),
    (211,'Kimppaosakas sekajäte'),
    (212,'Kimppaosakas biojäte'),
    (213,'Kimppaosakas muovipakkaus'),
    (214,'Kimppaosakas kartonkipakkaus'),
    (215,'Kimppaosakas lasipakkaus'),
    (216,'Kimppaosakas metalli'),
    (217,'Kimppaosakas monilokero'),
    (311,'Yhteyshenkilö kompostointi')
on conflict (id) do update set selite = excluded.selite;
