insert into jkr_koodistot.rakennusluokka_2018(koodi, selite) values
('0110', 'Omakotitalot'),
('0211', 'Osavuotiseen käyttöön soveltuvat vapaa-ajan asuinrakennukset'),
('1910', 'Saunarakennukset'),
('0210', 'Ympärivuotiseen käyttöön soveltuvat vapaa-ajan asuinrakennukset'),
('0112', 'Rivitalot'),
('0121', 'Asuinkerrostalot'),
('0111', 'Paritalot'),
('0120', 'Pienkerrostalot'),
('0910', 'Yleiskäyttöiset teollisuushallit'),
('0514', 'Kulkuneuvojen katokset'),
('0511', 'Ammattiliikenteen kaluston suojarakennukset'),
('0920', 'Teollisuus- ja pienteollisuustalot'),
('0319', 'Muut myymälärakennukset'),
('0512', 'Ammattiliikenteen kaluston huoltorakennukset'),
('0400', 'Toimistorakennukset'),
('0919', 'Muut teollisuuden tuotantorakennukset'),
('0521', 'Tietoliikenteen rakennukset'),
('1090', 'Energiansiirtorakennukset'),
('0310', 'Tukku- ja vähittäiskaupan myymälähallit'),
('0329', 'Muut majoitusliikerakennukset'),
('0820', 'Yleissivistävien oppilaitosten rakennukset'),
('0590', 'Muut liikenteen rakennukset'),
('0311', 'Kauppakeskukset ja liike- ja tavaratalot'),
('0911', 'Raskaan teollisuuden tehdasrakennukset'),
('0720', 'Seura- ja kerhorakennukset'),
('1110', 'Vedenotto-, vedenpuhdistus- ja vedenjakelurakennukset'),
('0620', 'Laitospalvelujen rakennukset'),
('0330', 'Ravintolarakennukset ja vastaavat liikerakennukset'),
('0749', 'Muut urheilu- ja liikuntarakennukset'),
('0810', 'Lasten päiväkodit'),
('0830', 'Ammatillisten oppilaitosten rakennukset'),
('1011', 'Lämpö- ja kylmäenergian tuotantorakennukset'),
('0140', 'Erityisryhmien asuinrakennukset'),
('0621', 'Avopalvelujen rakennukset'),
('0790', 'Muut kokoontumisrakennukset'),
('0713', 'Museot ja taidegalleriat'),
('0912', 'Elintarviketeollisuuden tuotantorakennukset'),
('0739', 'Muut uskonnollisten yhteisöjen rakennukset'),
('1311', 'Väestönsuojat'),
('0730', 'Uskonnonharjoittamisrakennukset'),
('0731', 'Seurakuntatalot'),
('1010', 'Sähköenergian tuotantorakennukset'),
('1310', 'Paloasemat'),
('0322', 'Loma-, lepo- ja virkistyskodit'),
('0130', 'Asuntolarakennukset'),
('0513', 'Pysäköintitalot ja -hallit'),
('1120', 'Jätteenkeruu-, jätteenkäsittely- ja jätteenvarastointirakennukset'),
('0712', 'Kirjastot ja arkistot'),
('0510', 'Asemarakennukset ja terminaalit'),
('0743', 'Urheilu- ja palloiluhallit'),
('0619', 'Muut terveydenhuoltorakennukset'),
('0320', 'Hotellit'),
('0610', 'Terveys- ja hyvinvointikeskukset'),
('0321', 'Motellit, hostellit ja vastaavat majoitusliikerakennukset'),
('0714', 'Näyttely- ja messuhallit'),
('0710', 'Teatterit, musiikki- ja kongressitalot'),
('0742', 'Monitoimihallit'),
('1319', 'Muut pelastustoimen rakennukset'),
('0740', 'Jäähallit'),
('1091', 'Energianvarastointirakennukset'),
('0741', 'Uimahallit'),
('0744', 'Stadion- ja katsomorakennukset'),
('0930', 'Metallimalmien käsittelyrakennukset'),
('0612', 'Erikoissairaalat ja laboratoriorakennukset'),
('0614', 'Kuntoutuslaitokset'),
('0520', 'Datakeskukset ja laitetilat'),
('0840', 'Korkeakoulurakennukset'),
('0841', 'Tutkimuslaitosrakennukset'),
('0891', 'Järjestöjen, liittojen, työnantajien ja vastaavat opetusrakennukset'),
('0611', 'Keskussairaalat'),
('1130', 'Materiaalien kierrätysrakennukset'),
('0613', 'Muut sairaalat'),
('0711', 'Elokuvateatterit')
on conflict (koodi) do update set selite = excluded.selite;