insert into jkr_koodistot.rakennuksenkayttotarkoitus(koodi, selite) values
    ('011','Yhden asunnon talot'),
    ('012','Kahden asunnon talot'),
    ('013','Muut erilliset pientalot'),
    ('021','Rivitalot'),
    ('022','Ketjutalot'),
    ('032','Luhtitalot'),
    ('039','Muut asuinkerrostalot'),
    ('041','Vapaa-ajan asuinrakennukset'),
    ('111','Myymälähallit'),
    ('112','Liike- ja tavaratalot, kauppakeskukset'),
    ('119','Muut myymälärakennukset'),
    ('121','Hotellit yms.'),
    ('123','Loma-, lepo- ja virkistyskodit'),
    ('124','Vuokrattavat lomamökit ja -osakkeet'),
    ('129','Muut majoitusliikerakennukset'),
    ('131','Asuntolat yms.'),
    ('139','Muut asuntolarakennukset'),
    ('141','Ravintolat yms.'),
    ('151','Toimistorakennukset'),
    ('161','Rautatie- ja linja-autoasemat, lento- ja satamaterminaalit'),
    ('162','Kulkuneuvojen suoja- ja huoltorakennukset'),
    ('163','Pysäköintitalot'),
    ('164','Tietoliikenteen rakennukset'),
    ('169','Muut liikenteen rakennukset'),
    ('211','Keskussairaalat'),
    ('213','Muut sairaalat'),
    ('214','Terveyskeskukset'),
    ('215','Terveydenhuollon erityislaitokset'),
    ('219','Muut terveydenhuoltorakennukset'),
    ('221','Vanhainkodit'),
    ('222','Lasten- ja koulukodit'),
    ('223','Kehitysvammaisten hoitolaitokset'),
    ('229','Muut huoltolaitosrakennukset'),
    ('231','Lasten päiväkodit'),
    ('239','Muualla luokittelemattomat sosiaalitoimen rakennukset'),
    ('241','Vankilat'),
    ('311','Teatterit, ooppera-, konsertti- ja kongressitalot'),
    ('312','Elokuvateatterit'),
    ('322','Kirjastot ja arkistot'),
    ('323','Museot ja taidegalleriat'),
    ('324','Näyttelyhallit'),
    ('331','Seura- ja kerhorakennukset yms.'),
    ('341','Kirkot, kappelit, luostarit ja rukoushuoneet'),
    ('342','Seurakuntatalot'),
    ('349','Muut uskonnollisten yhteisöjen rakennukset'),
    ('351','Jäähallit'),
    ('352','Uimahallit'),
    ('353','Tennis-, squash- ja sulkapallohallit'),
    ('354','Monitoimihallit ja muut urheiluhallit'),
    ('359','Muut urheilu- ja kuntoilurakennukset'),
    ('369','Muut kokoontumisrakennukset'),
    ('511','Yleissivistävien oppilaitosten rakennukset'),
    ('521','Ammatillisten oppilaitosten rakennukset'),
    ('531','Korkeakoulurakennukset'),
    ('532','Tutkimuslaitosrakennukset'),
    ('541','Järjestöjen, liittojen, työnantajien yms. opetusrakennukset'),
    ('549','Muualla luokittelemattomat opetusrakennukset'),
    ('611','Voimalaitosrakennukset'),
    ('613','Yhdyskuntatekniikan rakennukset'),
    ('691','Teollisuushallit'),
    ('692','Teollisuus- ja pienteollisuustalot'),
    ('699','Muut teollisuuden tuotantorakennukset'),
    ('711','Teollisuusvarastot'),
    ('712','Kauppavarastot'),
    ('719','Muut varastorakennukset'),
    ('721','Paloasemat'),
    ('722','Väestönsuojat'),
    ('729','Muut palo- ja pelastustoimen rakennukset'),
    ('811','Navetat, sikalat, kanalat yms.'),
    ('819','Eläinsuojat, ravihevostallit, maneesit yms.'),
    ('891','Viljankuivaamot ja viljan säilytysrakennukset'),
    ('892','Kasvihuoneet'),
    ('893','Turkistarhat'),
    ('899','Muut maa-, metsä- ja kalatalouden rakennukset'),
    ('931','Saunarakennukset'),
    ('941','Talousrakennukset'),
    ('999','Muualla luokittelemattomat rakennukset')
on conflict do nothing;
