ALTER TABLE jkr.sopimus
  DROP COLUMN IF EXISTS aluejatepiste_asiakas CASCADE;

-- ddl-end --
-- object: jkr_koodistot.sopimustyyppi | type: TABLE --
-- DROP TABLE IF EXISTS jkr_koodistot.sopimustyyppi CASCADE;
CREATE TABLE jkr_koodistot.sopimustyyppi (
  id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  selite text,
  CONSTRAINT sopimustyyppi_pk PRIMARY KEY (id)
);

INSERT INTO jkr_koodistot.sopimustyyppi (selite)
  VALUES ('Tyhjennyssopimus'), ('Kimppasopimus'), ('Aluekeräyssopimus'), ('Putkikeräyssopimus');

-- ddl-end --
ALTER TABLE jkr_koodistot.sopimustyyppi OWNER TO jkr_admin;

-- ddl-end --
-- object: uidx_selite | type: INDEX --
-- DROP INDEX IF EXISTS jkr_koodistot.uidx_selite CASCADE;
CREATE UNIQUE INDEX uidx_selite ON jkr_koodistot.sopimustyyppi USING btree (selite);

-- ddl-end --
-- object: sopimustyyppi_id | type: COLUMN --
-- ALTER TABLE jkr.sopimus DROP COLUMN IF EXISTS sopimustyyppi_id CASCADE;
ALTER TABLE jkr.sopimus
  ADD COLUMN sopimustyyppi_id smallint;

UPDATE
  jkr.sopimus s
SET
  sopimustyyppi_id = (
    SELECT
      id
    FROM
      jkr_koodistot.sopimustyyppi
    WHERE
      selite = 'Tyhjennyssopimus')
WHERE
  EXISTS (
    SELECT
      1
    FROM
      jkr.keraysvaline k
    WHERE
      k.sopimus_id = s.id);

UPDATE
  jkr.sopimus s
SET
  sopimustyyppi_id = (
    SELECT
      id
    FROM
      jkr_koodistot.sopimustyyppi
    WHERE
      selite = 'Kimppasopimus')
WHERE
  sopimustyyppi_id IS NULL
  AND kimppaisanta_kohde_id IS NOT NULL;

-- ddl-end --
-- [ Changed objects ] --
ALTER TABLE jkr.sopimus
  ALTER COLUMN jatetyyppi_id DROP NOT NULL;

-- ddl-end --
-- [ Created foreign keys ] --
-- object: sopimustyyppi_fk | type: CONSTRAINT --
-- ALTER TABLE jkr.sopimus DROP CONSTRAINT IF EXISTS sopimustyyppi_fk CASCADE;
ALTER TABLE jkr.sopimus
  ADD CONSTRAINT sopimustyyppi_fk FOREIGN KEY (sopimustyyppi_id) REFERENCES jkr_koodistot.sopimustyyppi (id) MATCH FULL ON DELETE CASCADE ON UPDATE CASCADE;

-- ddl-end --
