CREATE OR REPLACE FUNCTION JKR.Asuinkiinteisto_kohteet_vaarilla_ominaisuuksilla () RETURNS TABLE (KOHDE_ID INTEGER, PRT TEXT) AS $$
SELECT
	K.ID,
	R.PRT
FROM
	JKR.KOHDE K
	LEFT JOIN JKR.KOHTEEN_RAKENNUKSET KR ON KR.KOHDE_ID = K.ID
	LEFT JOIN JKR.RAKENNUS R ON R.ID = KR.RAKENNUS_ID
WHERE
	KOHDETYYPPI_ID = 7
	AND NOT (
		R.HUONEISTOMAARA > 0
		OR (
			R.RAKENNUKSENKAYTTOTARKOITUS_KOODI::INTEGER >= 010
			AND R.RAKENNUKSENKAYTTOTARKOITUS_KOODI::INTEGER <= 041
		)
		OR (
			R.RAKENNUSLUOKKA_2018::INTEGER >= 0110
			AND R.RAKENNUSLUOKKA_2018::INTEGER <= 0211
		)
		OR R.RAKENNUKSENOLOTILA_KOODI::INTEGER = 1
	);
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION JKR.Asuinkiinteisto_kohteet_vaarilla_ominaisuuksilla () RETURNS TABLE (KOHDE_ID INTEGER, PRT TEXT) AS $$
SELECT
	K.ID,
	R.PRT
FROM
	JKR.KOHDE K
	LEFT JOIN JKR.KOHTEEN_RAKENNUKSET KR ON KR.KOHDE_ID = K.ID
	LEFT JOIN JKR.RAKENNUS R ON R.ID = KR.RAKENNUS_ID
WHERE
	KOHDETYYPPI_ID = 7
	AND NOT (
		R.HUONEISTOMAARA > 0
		OR (
			R.RAKENNUKSENKAYTTOTARKOITUS_KOODI::INTEGER >= 010
			AND R.RAKENNUKSENKAYTTOTARKOITUS_KOODI::INTEGER <= 041
		)
		OR (
			R.RAKENNUSLUOKKA_2018::INTEGER >= 0110
			AND R.RAKENNUSLUOKKA_2018::INTEGER <= 0211
		)
		OR R.RAKENNUKSENOLOTILA_KOODI::INTEGER = 1
	);
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION JKR.Muu_kohteet_vaarilla_ominaisuuksilla () RETURNS TABLE (KOHDE_ID INTEGER, PRT TEXT) AS $$
SELECT
	K.ID,
	R.PRT
FROM
	JKR.KOHDE K
	LEFT JOIN JKR.KOHTEEN_RAKENNUKSET KR ON KR.KOHDE_ID = K.ID
	LEFT JOIN JKR.RAKENNUS R ON R.ID = KR.RAKENNUS_ID
WHERE
	KOHDETYYPPI_ID = 8
	AND (
		R.HUONEISTOMAARA > 0
		OR (
			R.RAKENNUKSENKAYTTOTARKOITUS_KOODI::INTEGER >= 010
			AND R.RAKENNUKSENKAYTTOTARKOITUS_KOODI::INTEGER <= 041
		)
		OR (
			R.RAKENNUSLUOKKA_2018::INTEGER >= 0110
			AND R.RAKENNUSLUOKKA_2018::INTEGER <= 0211
		)
		OR R.RAKENNUKSENOLOTILA_KOODI::INTEGER = 1
	);
$$ LANGUAGE SQL STABLE;


CREATE OR REPLACE FUNCTION JKR.KOHTEET_PAATTYNEILLA_RAKENNUKSILLA () RETURNS TABLE (KOHDE_ID INTEGER, PRT TEXT) AS $$
SELECT
	K.ID,
	R.PRT
FROM
	JKR.RAKENNUS R
	LEFT JOIN JKR.KOHTEEN_RAKENNUKSET KR ON KR.RAKENNUS_ID = R.ID
	LEFT JOIN JKR.KOHDE K ON KR.KOHDE_ID = K.ID
WHERE
	R.KAYTOSTAPOISTO_PVM IS NULL
	AND K.LOPPUPVM IS NOT NULL
ORDER BY
	K.ID;
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION JKR.RAKENNUKSET_PAATTYNEILLA_KOHTEILLA () RETURNS TABLE (KOHDE_ID INTEGER, PRT TEXT) AS $$
SELECT
	K.ID,
	R.PRT
FROM
	JKR.KOHDE K
	LEFT JOIN JKR.KOHTEEN_RAKENNUKSET KR ON KR.KOHDE_ID = K.ID
	LEFT JOIN JKR.RAKENNUS R ON KR.RAKENNUS_ID = R.ID
WHERE
	K.LOPPUPVM IS NOT NULL
	AND PRT IS NOT NULL
	AND KAYTOSTAPOISTO_PVM IS NULL
ORDER BY
	K.ID;
	$$ LANGUAGE SQL STABLE;


CREATE OR REPLACE FUNCTION JKR.Rakennukset_usealla_kohteella() RETURNS TABLE (RAKENNUS_ID INTEGER, prt TEXT, Kohteita INTEGER) AS $$
SELECT
	R.ID,
	R.prt,
	COUNT(KR.KOHDE_ID) AS KOHTEITA
FROM
	JKR.RAKENNUS R
	JOIN JKR.KOHTEEN_RAKENNUKSET KR ON KR.RAKENNUS_ID = R.ID
	JOIN JKR.KOHDE K1 ON K1.ID = KR.KOHDE_ID
GROUP BY
	R.ID,
	R.PRT,
	K1.ALKUPVM,
	K1.LOPPUPVM
HAVING
	COUNT(KR.KOHDE_ID) > 1
ORDER BY
	R.ID;
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION JKR.Velvoitteella_ei_ole_yhteenvetoa() RETURNS TABLE (KOHDE_ID INTEGER) AS $$
SELECT DISTINCT k.id
FROM jkr.kohde k
JOIN jkr.velvoite v ON v.kohde_id = k.id
WHERE NOT EXISTS (
    SELECT 1
    FROM jkr.velvoiteyhteenveto vy
	LEFT JOIN jkr.velvoiteyhteenveto_status vys ON vys.velvoiteyhteenveto_id = vy.id
    WHERE vy.kohde_id = k.id
);
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION JKR.velvoite_toteutumatta_jatelajeittain() RETURNS TABLE (RAKENNUS_ID INTEGER) AS $$
SELECT DISTINCT ON (k.id, 
    CASE WHEN vm.jatetyyppi_id = 14 THEN 2 ELSE vm.jatetyyppi_id END)
    k.id AS kohde_id
FROM jkr.kohde k
JOIN jkr.velvoite v ON v.kohde_id = k.id
JOIN jkr.velvoitemalli vm ON vm.id = v.velvoitemalli_id
JOIN jkr.velvoite_status vs ON vs.velvoite_id = v.id

-- Anti-join: skip kohde/jatetyyppi combinations that have ok = true
LEFT JOIN (
    SELECT
        v2.kohde_id,
        CASE WHEN vm2.jatetyyppi_id = 14 THEN 2 ELSE vm2.jatetyyppi_id END AS normalized_jatetyyppi_id
    FROM jkr.velvoite v2
    JOIN jkr.velvoitemalli vm2 ON vm2.id = v2.velvoitemalli_id
    JOIN jkr.velvoite_status vs2 ON vs2.velvoite_id = v2.id
    WHERE vs2.ok = TRUE
    GROUP BY v2.kohde_id, normalized_jatetyyppi_id
) existing_ok 
ON existing_ok.kohde_id = k.id
AND existing_ok.normalized_jatetyyppi_id = 
    CASE WHEN vm.jatetyyppi_id = 14 THEN 2 ELSE vm.jatetyyppi_id END

WHERE existing_ok.kohde_id IS NULL
ORDER BY k.id, 
    CASE WHEN vm.jatetyyppi_id = 14 THEN 2 ELSE vm.jatetyyppi_id END,
    LOWER(vs.jakso) DESC;
$$ LANGUAGE SQL STABLE;



CREATE OR REPLACE FUNCTION JKR.TESTIDATAN_TARKISTUS () RETURNS TABLE (
	RAKENNUKSET_YHDELLA_KOHTEELLA TEXT,
	KOMPOSTORIEN_KOHTEET_MUODOSTUVAT TEXT,
	KOMPOSTORIT_ILMAN_KOHTEITA TEXT,
	PAATTYNEET_KOHTEET_RAKENNUKSILLA TEXT,
	PAATTYNEET_RAKENNUKSET_KOHTEILLA TEXT,
	ASUINKIINTEISTO_KOHDETYYPPI_OIKEIN TEXT,
	MUU_KOHDETYYPPI_OIKEIN TEXT,
	KOHTEELLA_ON_VELVOITEYHTEENVETO_JOS_ON_VELVOITE TEXT,
	VELVOITESTATUKSEN_TULEE_OLLA_OK_JATELAJIN_VELVOITTEISTA TEXT
) AS $$
SELECT
	(
		SELECT
			COUNT(*)
		FROM
			JKR.RAKENNUKSET_USEALLA_KOHTEELLA ()
	) = 0 AS "Rakennukset ilman useaa kohdetta",
	(
		SELECT
			COUNT(*)
		FROM
			JKR.KOMPOSTORIN_KOHTEET
	) >= 4000 AS "kk_maara",
	(
		SELECT
			COUNT(*)
		FROM
			JKR.KOMPOSTORI K
			LEFT JOIN JKR.KOMPOSTORIN_KOHTEET KK ON KK.KOMPOSTORI_ID = K.ID
		WHERE
			KK.KOHDE_ID IS NULL
	) = 0 AS "Ei orpoja kompostoreja",
	(
		SELECT
			COUNT(*)
		FROM
			JKR.RAKENNUKSET_PAATTYNEILLA_KOHTEILLA ()
	) = 0 AS "Ei Rakennusta paattyneessä kohteessa",
	(
		SELECT
			COUNT(*)
		FROM
			JKR.KOHTEET_PAATTYNEILLA_RAKENNUKSILLA ()
	) = 0 AS "Ei kohdetta päättyneellä rakennuksella",
	(
		SELECT
			COUNT(*)
		FROM
			JKR.MUU_KOHTEET_VAARILLA_OMINAISUUKSILLA ()
	) = 0 AS "Ei muita kohteita asuinkiinteistökriteerien kohteilla",
	(
		SELECT
			COUNT(*)
		FROM
			JKR.ASUINKIINTEISTO_KOHTEET_VAARILLA_OMINAISUUKSILLA ()
	) = 0 AS "EI Asuinkiinteistöä ilman oikeita kriteereitä",
	(
		SELECT
			COUNT(*)
		FROM
			JKR.Velvoitteella_ei_ole_yhteenvetoa ()
	) = 0 AS "Velvoitteilla on yhteenveto",
	( -- At least one velvoite status ok=true per kohde/jätelaji, currently 160 exceptions in test data
		SELECT
			COUNT(*)
		FROM
			JKR.velvoite_toteutumatta_jatelajeittain ()
	) <= 160 AS "Vähintään yksi toteutunut velvoite kohteella per jätelaji"
$$ LANGUAGE SQL STABLE;