\set copy_command '\\copy tmp_report_result TO ' :'csv_path' ' WITH CSV HEADER'

CREATE TEMP TABLE tmp_report_result(
    kohde_id INTEGER,
    tarkastelupvm DATE,
    "Kohteen rakennuksen 1 sijaintikunta" TEXT,
    huoneistolkm BIGINT,
    "yli 10 000 taajama" TEXT,
    "200 asukkaan taajama" TEXT,
    "Komposti-ilmoituksen tekijan nimi" text,
    "Sekajatteen tilaajan nimi" text,
    "Sekajatteen tilaajan katuosoite" text,
    "Sekajatteen tilaajan postinumero" text,
    "Sekajatteen tilaajan postitoimipaikka" text,
    "Salpakierron tilaajan nimi" text,
    "Salpakierron tilaajan katuosoite" text,
    "Salpakierron postinumero" text,
    "Salpakierron postitoimipaikka" text,
    "Omistaja 1 nimi" text,
    "Omistaja 1 katuosoite" text,
    "Omistaja 1 postinumero" text,
    "Omistaja 1 postitoimipaikka" text,
    "Omistaja 2 nimi" text,
    "Omistaja 2 katuosoite" text,
    "Omistaja 2 postinumero" text,
    "Omistaja 2 postitoimipaikka" text,
    "Omistaja 3 nimi" text,
    "Omistaja 3 katuosoite" text,
    "Omistaja 3 postinumero" text,
    "Omistaja 3 postitoimipaikka" text,
    "Vanhimman asukkaan nimi" text,
    "Velvoitteen tallennuspvm" date,
    Velvoiteyhteenveto text,
    Sekajatevelvoite text,
    Biojatevelvoite text,
    Muovipakkausvelvoite text,
    Kartonkipakkausvelvoite text,
    Lasipakkausvelvoite text,
    Metallipakkausvelvoite text,
    Muovi date,
    Kartonki date,
    Metalli date,
    Lasi date,
    Biojate date,
    Monilokero date,
    Sekajate date,
    Akp date,
    Kompostoi date,
    "Perusmaksupaatos voimassa" date,
    "Perusmaksupaatos" text,
    "Tyhjennysvalipaatos voimassa" date,
    "Tyhjennysvalipaatos" text,
    "Akp-kohtuullistaminen voimassa" date,
    "Akp-kohtuullistaminen" text,
    "Keskeytys voimassa" date,
    "Keskeytys" text,
    "Erilliskeraysvelvoitteesta poikkeaminen voimassa" date,
    "Erilliskeraysvelvoitteesta poikkeaminen" text,
    "PRT 1" text,
    "Kayttotila 1" text,
    "Kayttotarkoitus 1" text,
    Katuosoite text,
    Postinumero text,
    Postitoimipaikka text,
    Sijaintikiinteisto text,
    "X-koordinaatti" float,
    "Y-koordinaatti" float,
    "PRT 2" text,
    "Kayttotila 2" text,
    "Kayttotarkoitus 2" text,
    "PRT 3" text,
    "Kayttotila 3" text,
    "Kayttotarkoitus 3" text,
    "PRT 4" text,
    "Kayttotila 4" text,
    "Kayttotarkoitus 4" text,
    "PRT 5" text,
    "Kayttotila 5" text,
    "Kayttotarkoitus 5" text,
    "PRT 6" text,
    "Kayttotila 6" text,
    "Kayttotarkoitus 6" text,
    "PRT 7" text,
    "Kayttotila 7" text,
    "Kayttotarkoitus 7" text,
    "PRT 8" text,
    "Kayttotila 8" text,
    "Kayttotarkoitus 8" text,
    "PRT 9" text,
    "Kayttotila 9" text,
    "Kayttotarkoitus 9" text,
    "PRT 10" text,
    "Kayttotila 10" text,
    "Kayttotarkoitus 10" text,
    "PRT 11" text,
    "Kayttotila 11" text,
    "Kayttotarkoitus 11" text,
    "PRT 12" text,
    "Kayttotila 12" text,
    "Kayttotarkoitus 12" text,
    "PRT 13" text,
    "Kayttotila 13" text,
    "Kayttotarkoitus 13" text,
    "PRT 14" text,
    "Kayttotila 14" text,
    "Kayttotarkoitus 14" text,
    "PRT 15" text,
    "Kayttotila 15" text,
    "Kayttotarkoitus 15" text,
    "PRT 16" text,
    "Kayttotila 16" text,
    "Kayttotarkoitus 16" text,
    "PRT 17" text,
    "Kayttotila 17" text,
    "Kayttotarkoitus 17" text       
);

INSERT INTO tmp_report_result
SELECT * FROM jkr.print_report(
    :'check_date',
    CASE WHEN :'municipality' = '*' THEN NULL ELSE :'municipality' END,
    :'count_apartments',
    CASE WHEN :'taajama_size' = 10000 THEN TRUE ELSE NULL END,
    CASE WHEN :'taajama_size' = 200 THEN TRUE ELSE NULL END
);

:copy_command
