INSERT INTO jkr.velvoitemalli(id, selite, saanto, tayttymissaanto, jatetyyppi_id, alkupvm, loppupvm, kuvaus, prioriteetti)
VALUES
    (
        3,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte puuttuu',
        16
    ),
    (
        4,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_yli_4_vk_ei_bio',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte väärä tyhjennysväli',
        11
    ),
    (
        5,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_0_tai_yli_16_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte väärä tyhjennysväli',
        11
    ),
    (
        6,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_yli_16_vk_pidentava_ei_ok',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte väärä tyhjennysväli',
        11
    ),
    (
        7,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_yli_16_vk_ei_bio_pidentava_ok',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte väärä tyhjennysväli',
        11
    ),
    (
        8,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_alle_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte kunnossa',
        6
    ),
    (
        9,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_enint_16_vk_bio_on',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte kunnossa',
        6
    ),
    (
        10,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_enint_16_vk_kompostointi_ok',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte kunnossa',
        6
    ),
    (
        11,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_yli_16_vk_kompostointi_ok_pidentava_ok',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte kunnossa',
        6
    ),
    (
        12,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_seka_yli_16_vk_bio_on_pidentava_ok',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Sekajäte'),
        '2022-1-1',
        NULL,
        'Sekajäte kunnossa',
        6
    ),
    (
        13,
        'Biojäte',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_bio_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2022-1-1',
        '2023-12-31',
        'Biojäte puuttuu',
        16
    ),
    (
        14,
        'Biojäte',
        'v_enint_4_huoneistoa_biojatteen_erilliskeraysalue',
        'kohteet_joilla_bio_puuttuu_ei_kompostointia',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2022-1-1',
        '2023-12-31',
        'Biojäte puuttuu',
        16
    ),
    (
        15,
        'Biojäte',
        'v_erilliskeraysalueet',
        'kohteet_joilla_bio_0_tai_yli_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2022-1-1',
        '2023-12-31',
        'Biojäte väärä tyhjennysväli',
        11
    ),
    (
        16,
        'Biojäte',
        'v_erilliskeraysalueet',
        'kohteet_joilla_bio_enint_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2022-1-1',
        '2023-12-31',
        'Biojäte kunnossa',
        6
    ),
    (
        17,
        'Biojäte',
        'v_enint_4_huoneistoa_biojatteen_erilliskeraysalue',
        'kohteet_joilla_kompostointi_voimassa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2022-1-1',
        '2023-12-31',
        'Biojäte kunnossa',
        6
    ),
    (
        18,
        'Muovipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_muovi_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Muovipakkaus'),
        '2022-1-1',
        NULL,
        'Muovipakkaus puuttuu',
        16
    ),
    (
        19,
        'Muovipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_muovi_yli_12_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Muovipakkaus'),
        '2022-1-1',
        NULL,
        'Muovipakkaus väärä tyhjennysväli',
        11
    ),
    (
        20,
        'Muovipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_muovi_enintaan_12_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Muovipakkaus'),
        '2022-1-1',
        NULL,
        'Muovipakkaus kunnossa',
        6
    ),
    (
        21,
        'Kartonkipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_kartonki_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Kartonkipakkaus'),
        '2022-1-1',
        NULL,
        'Kartonkipakkaus puuttuu',
        16
    ),
    (
        22,
        'Kartonkipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_kartonki_yli_12_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Kartonkipakkaus'),
        '2022-1-1',
        NULL,
        'Kartonkipakkaus väärä tyhjennysväli',
        11
    ),
    (
        23,
        'Kartonkipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_kartonki_enintaan_12_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Kartonkipakkaus'),
        '2022-1-1',
        NULL,
        'Kartonkipakkaus kunnossa',
        6
    ),
    (
        24,
        'Lasipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_lasi_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Lasipakkaus'),
        '2022-1-1',
        NULL,
        'Lasipakkaus puuttuu',
        16
    ),
    (
        25,
        'Lasipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_lasi_yli_26_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Lasipakkaus'),
        '2022-1-1',
        NULL,
        'Lasipakkaus väärä tyhjennysväli',
        11
    ),
    (
        26,
        'Lasipakkaus',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_lasi_enintaan_26_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Lasipakkaus'),
        '2022-1-1',
        NULL,
        'Lasipakkaus kunnossa',
        6
    ),
    (
        27,
        'Metalli',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_metalli_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Metalli'),
        '2022-1-1',
        NULL,
        'Metalli puuttuu',
        16
    ),
    (
        28,
        'Metalli',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_metalli_yli_26_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Metalli'),
        '2022-1-1',
        NULL,
        'Metalli väärä tyhjennysväli',
        11
    ),
    (
        29,
        'Metalli',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_metalli_enintaan_26_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Metalli'),
        '2022-1-1',
        NULL,
        'Metalli kunnossa',
        6
    ),
    (
        30,
        'Sekajäte',
        'kohde',
        'kohteet_joilla_on_aluekerays_kuljetuksia_tai_sopimuksia',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Aluekeräyspiste'),
        '2022-1-1',
        NULL,
        'Sekajäte kunnossa',
        6
    ),
    (
        31,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_jotka_ovat_viemariverkossa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Viemäriverkostossa',
        1
    ),
    (
        32,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joiden_rakennukset_vapautettu_eivat_viemariverkossa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Vapautettu',
        6
    ),
    (
        33,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_kantovesi_tieto',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Kantovesi',
        6
    ),
    (
        34,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_saostusailio_tai_pienpuhdistamo_ei_harmaata_vett',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Lietteenkuljetus kunnossa saostussäiliö tai pienpuhdistamo',
        6
    ),
    (
        35,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_saostusailio_tyhja_ja_pienpuhdistamo_kompostoint',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Lietteenkuljetus kunnossa saostussäiliö tai pienpuhdistamo',
        6
    ),
    (
        36,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteella_lietekuljetus_ok_umpisailio_tai_ei_tietoa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Lietteenkuljetus kunnossa umpisäiliö tai ei tietoa',
        6
    ),
    (
        37,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_vain_harmaat_vedet',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Lietteenkuljetus kunnossa harmaat vedet',
        6
    ),
    (
        38,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_saostusai_tai_pienpuh_vaara_vali_ei_harmaata_vet',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Väärä tyhjennysväli saostussäiliö tai pienpuhdistamo',
        11
    ),
    (
        39,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteella_lietekuljetus_vaara_vali_umpisailio_tai_ei_tietoa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Väärä tyhjennysväli umpisäiliö tai ei tietoa',
        11
    ),
    (
        40,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_vaara_tyhjennysvali_vain_harmaat_vedet',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Väärä tyhjennysväli harmaat vedet',
        11
    ),
    (
        41,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_saostusai_tai_pienpuh_ei_lietekuljetus_harmaata',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Ei lietteenkuljetusta saostussäiliö tai pienpuhdistamo',
        16
    ),
    (
        42,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteella_ei_lietteenkuljetusta_umpisailio_tai_ei_tietoa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Ei lietteenkuljetusta umpisäiliö tai ei tietoa',
        16
    ),
    (
        43,
        'Lietevelvoite',
        'v_bio_hapa_asuinkiinteisto',
        'kohteet_joilla_ei_lietteenkuljetusta_harmaat_vedet',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Liete'),
        '2022-1-1',
        NULL,
        'Ei lietteenkuljetusta harmaat vedet',
        16
    ),
    (
        44,
        'Biojäte',
        'v_biohapa_kohde',
        'kohteet_joilla_bio_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte puuttuu',
        16
    ),
    (
        45,
        'Biojäte',
        'v_biohapa_kohde',
        'kohteet_joilla_bio_puuttuu_ei_kompostointia',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte puuttuu',
        16
    ),
    (
        46,
        'Biojäte',
        'v_biohapa_kohde',
        'kohteet_joilla_bio_0_tai_yli_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte väärä tyhjennysväli',
        11
    ),
    (
        47,
        'Biojäte',
        'v_biohapa_kohde',
        'kohteet_joilla_bio_enint_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte kunnossa',
        6
    ),
    (
        48,
        'Biojäte',
        'v_biohapa_kohde',
        'kohteet_joilla_kompostointi_voimassa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte kunnossa',
        6
    ),
    -- Asuinkiinteistöt: ≥5 huoneistoa, hyötyjätteiden erilliskeräysalue (taajama)
    (
        49,
        'Biojäte',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_bio_puuttuu',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte puuttuu',
        16
    ),
    (
        50,
        'Biojäte',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_bio_0_tai_yli_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte väärä tyhjennysväli',
        11
    ),
    (
        51,
        'Biojäte',
        'v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue',
        'kohteet_joilla_bio_enint_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte kunnossa',
        6
    ),
    -- Asuinkiinteistöt: 0-4 huoneistoa, biojätteen erilliskeräysalue (taajama ≥10000)
    (
        52,
        'Biojäte',
        'v_enint_4_huoneistoa_biojatteen_erilliskeraysalue',
        'kohteet_joilla_bio_puuttuu_ei_kompostointia',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte puuttuu',
        16
    ),
    (
        53,
        'Biojäte',
        'v_enint_4_huoneistoa_biojatteen_erilliskeraysalue',
        'kohteet_joilla_bio_0_tai_yli_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte väärä tyhjennysväli',
        11
    ),
    (
        54,
        'Biojäte',
        'v_enint_4_huoneistoa_biojatteen_erilliskeraysalue',
        'kohteet_joilla_bio_enint_4_vk',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte kunnossa',
        6
    ),
    (
        55,
        'Biojäte',
        'v_enint_4_huoneistoa_biojatteen_erilliskeraysalue',
        'kohteet_joilla_kompostointi_voimassa',
        (SELECT id FROM jkr_koodistot.jatetyyppi WHERE selite = 'Biojäte'),
        '2024-1-1',
        NULL,
        'Biojäte kunnossa',
        6
    )

ON CONFLICT DO NOTHING;

-- LAH-591: Päivitetään saannon_selite ja tayttymissaannon_selite kaikille olemassa
-- oleville velvoitemalleille.
UPDATE jkr.velvoitemalli vm
SET saannon_selite = v.saannon_selite,
    tayttymissaannon_selite = v.tayttymissaannon_selite
FROM (VALUES
    -- Saannon_selite avaa saanto-kentän näkymän tai erikoisarvon 'kohde' kohderyhmän:
    --   'kohde'                                              = sääntöä ei rajata, sovelletaan kaikkiin kohteisiin
    --   v_vah_5_huoneistoa_hyotyjatteen_erilliskeraysalue    = >=5 huoneiston kohteet taajamassa (hyötyjäte)
    --   v_enint_4_huoneistoa_biojatteen_erilliskeraysalue    = <=4 huoneiston kohteet >=10 000 as. taajamassa (biojäte)
    --   v_erilliskeraysalueet                                = molempien erilliskeräysalueiden yhdistelmä
    --   v_bio_hapa_asuinkiinteisto                           = kohdetyyppi-id 5/6/7 (HAPA/BIOHAPA/Asuinkiinteistö)
    --   v_biohapa_kohde                                      = kohdetyyppi-id 6 (BIOHAPA)
    (3,  'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin riippumatta kohdetyypistä, sijainnista tai huoneistomäärästä.',
         'Kohteelta puuttuu voimassa oleva sekajätesopimus (suoraan tai kimppasopimuksen kautta) eikä sillä ole voimassa olevaa vapauttavaa, keskeyttävää tai tyhjennysväliä pidentävää päätöstä.'),
    (4,  'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on yli 4 viikkoa, kohteella ei ole voimassa olevaa biojätesopimusta tai kompostointi-ilmoitusta eikä vapauttavaa, keskeyttävää tai pidentävää päätöstä.'),
    (5,  'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on 0 tai yli 16 viikkoa eikä kohteella ole voimassa olevaa vapauttavaa, keskeyttävää tai pidentävää päätöstä.'),
    (6,  'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Kohteella on voimassa oleva tyhjennysväliä pidentävä päätös, mutta sekajätesopimuksen tyhjennysväli ylittää sekä päätöksen sallitun rajan että 16 viikkoa.'),
    (7,  'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on yli 16 viikkoa pidentävän päätöksen sallimissa rajoissa, mutta kohteella ei ole voimassa olevaa biojätesopimusta tai kompostointi-ilmoitusta.'),
    (8,  'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on alle 4 viikkoa (1-3 vk).'),
    (9,  'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on enintään 16 viikkoa ja kohteella on voimassa oleva biojätesopimus (suoraan tai kimppasopimuksen kautta).'),
    (10, 'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on enintään 16 viikkoa ja kohteella on voimassa oleva kompostointi-ilmoitus.'),
    (11, 'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on yli 16 viikkoa pidentävän päätöksen sallimissa rajoissa ja kohteella on voimassa oleva kompostointi-ilmoitus.'),
    (12, 'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Sekajätteen tyhjennysväli on yli 16 viikkoa pidentävän päätöksen sallimissa rajoissa ja kohteella on voimassa oleva biojätesopimus.'),
    (13, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kohteelta puuttuu voimassa oleva biojätesopimus (suoraan tai kimppasopimuksen kautta).'),
    (14, 'Biojätteen erilliskeräysalueen kohteet: kohteella on rakennus vähintään 10 000 asukkaan taajamassa ja kohteen rakennusten huoneistomäärä on yhteensä enintään 4.',
         'Kohteelta puuttuu voimassa oleva biojätesopimus eikä sillä ole voimassa olevaa kompostointi-ilmoitusta.'),
    (15, 'Erilliskeräysalueen kohteet: yhdistelmä biojätteen (enintään 4 huoneistoa, taajaman väestö >=10 000) ja hyötyjätteen (vähintään 5 huoneistoa, mikä tahansa taajama) erilliskeräysalueiden kohteista.',
         'Biojätteen tyhjennysväli on 0 tai yli 4 viikkoa.'),
    (16, 'Erilliskeräysalueen kohteet: yhdistelmä biojätteen (enintään 4 huoneistoa, taajaman väestö >=10 000) ja hyötyjätteen (vähintään 5 huoneistoa, mikä tahansa taajama) erilliskeräysalueiden kohteista.',
         'Biojätteen tyhjennysväli on enintään 4 viikkoa (1-4 vk).'),
    (17, 'Biojätteen erilliskeräysalueen kohteet: kohteella on rakennus vähintään 10 000 asukkaan taajamassa ja kohteen rakennusten huoneistomäärä on yhteensä enintään 4.',
         'Kohteella on voimassa oleva kompostointi-ilmoitus.'),
    (18, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kohteelta puuttuu voimassa oleva muovipakkaussopimus (suoraan tai kimppasopimuksen kautta).'),
    (19, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Muovipakkauksen tyhjennysväli on yli 12 viikkoa.'),
    (20, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Muovipakkauksen tyhjennysväli on enintään 12 viikkoa.'),
    (21, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kohteelta puuttuu voimassa oleva kartonkipakkaussopimus (suoraan tai kimppasopimuksen kautta).'),
    (22, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kartonkipakkauksen tyhjennysväli on yli 12 viikkoa.'),
    (23, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kartonkipakkauksen tyhjennysväli on enintään 12 viikkoa.'),
    (24, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kohteelta puuttuu voimassa oleva lasipakkaussopimus (suoraan tai kimppasopimuksen kautta).'),
    (25, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Lasipakkauksen tyhjennysväli on yli 26 viikkoa.'),
    (26, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Lasipakkauksen tyhjennysväli on enintään 26 viikkoa.'),
    (27, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kohteelta puuttuu voimassa oleva metallisopimus (suoraan tai kimppasopimuksen kautta).'),
    (28, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Metallin tyhjennysväli on yli 26 viikkoa.'),
    (29, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Metallin tyhjennysväli on enintään 26 viikkoa.'),
    (30, 'Sääntöä ei rajata näkymällä - sääntöä sovelletaan kaikkiin kohteisiin.',
         'Kohteella on voimassa oleva aluekeräyssopimus tai aluekeräyskuljetus.'),
    (31, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohde sijaitsee viemäriverkostossa eikä sillä ole muita kaivotyyppejä (saostussäiliö, pienpuhdistamo, umpisäiliö, harmaavesi tai kantovesi).'),
    (32, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohde ei ole viemäriverkostossa ja sen velvoiterakennukset on vapautettu jätteenkuljetuksesta voimassa olevalla myönteisellä AKP- tai Perusmaksupäätöksellä.'),
    (33, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on voimassa oleva kantovesikaivotieto eikä muita kaivotyyppejä, viemäriverkostoa tai vapautusta.'),
    (34, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on saostussäiliö tai pienpuhdistamo, lieteastia on tyhjennetty enintään 5 kvartaalin sisällä, eikä harmaavesikaivoa.'),
    (35, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on vain pienpuhdistamo (ei saostussäiliötä eikä umpisäiliötä) ja voimassa oleva lietteen kompostointi-ilmoitus.'),
    (36, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella ei ole saostussäiliö-, pienpuhdistamo- tai harmaavesikaivotietoa (umpisäiliö tai ei tietoa) ja lietekuljetus on tehty edellisen 6 kvartaalin (18 kk) sisällä.'),
    (37, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on harmaavesikaivo ja harmaavesikuljetus on tehty edellisen 11 kvartaalin (33 kk) sisällä.'),
    (38, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on saostussäiliö tai pienpuhdistamo, ei harmaavesikaivoa, ja viimeisin lietekuljetus 6-9 kvartaalin (18-27 kk) takana (väärä tyhjennysväli).'),
    (39, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella ei ole saostussäiliö-, pienpuhdistamo- tai harmaavesikaivotietoa ja viimeisin lietekuljetus on 10-13 kvartaalin (30-39 kk) takana (väärä tyhjennysväli).'),
    (40, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on harmaavesikaivo ja viimeisin harmaavesikuljetus on 13-15 kvartaalin (39-45 kk) takana (väärä tyhjennysväli).'),
    (41, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on saostussäiliö tai pienpuhdistamo, ei harmaavesikaivoa, eikä lainkaan lietekuljetusta edellisen 6 kvartaalin (18 kk) sisällä.'),
    (42, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella ei ole tunnettua kaivotyyppiä (umpisäiliö tai ei tietoa) eikä lainkaan lietekuljetusta edellisen 10 kvartaalin (30 kk) sisällä.'),
    (43, 'Lietevelvoitteiden kohderyhmä: HAPA- (kohdetyyppi-id 5), BIOHAPA- (id 6) ja Asuinkiinteistö-tyypin (id 7) kohteet.',
         'Kohteella on harmaavesikaivo eikä lainkaan harmaavesikuljetusta edellisen 15 kvartaalin (45 kk) sisällä.'),
    (44, 'BIOHAPA-kohteet (kohdetyyppi-id 6). Biohapa-kohteille kohdistetaan biojätevelvoite riippumatta siitä, sijaitsevatko ne erilliskeräysalueella.',
         'Kohteelta puuttuu voimassa oleva biojätesopimus (suoraan tai kimppasopimuksen kautta).'),
    (45, 'BIOHAPA-kohteet (kohdetyyppi-id 6). Biohapa-kohteille kohdistetaan biojätevelvoite riippumatta siitä, sijaitsevatko ne erilliskeräysalueella.',
         'Kohteelta puuttuu voimassa oleva biojätesopimus eikä sillä ole voimassa olevaa kompostointi-ilmoitusta.'),
    (46, 'BIOHAPA-kohteet (kohdetyyppi-id 6). Biohapa-kohteille kohdistetaan biojätevelvoite riippumatta siitä, sijaitsevatko ne erilliskeräysalueella.',
         'Biojätteen tyhjennysväli on 0 tai yli 4 viikkoa.'),
    (47, 'BIOHAPA-kohteet (kohdetyyppi-id 6). Biohapa-kohteille kohdistetaan biojätevelvoite riippumatta siitä, sijaitsevatko ne erilliskeräysalueella.',
         'Biojätteen tyhjennysväli on enintään 4 viikkoa (1-4 vk).'),
    (48, 'BIOHAPA-kohteet (kohdetyyppi-id 6). Biohapa-kohteille kohdistetaan biojätevelvoite riippumatta siitä, sijaitsevatko ne erilliskeräysalueella.',
         'Kohteella on voimassa oleva kompostointi-ilmoitus.'),
    (49, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Kohteelta puuttuu voimassa oleva biojätesopimus (suoraan tai kimppasopimuksen kautta).'),
    (50, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Biojätteen tyhjennysväli on 0 tai yli 4 viikkoa.'),
    (51, 'Hyötyjätteen erilliskeräysalueen kohteet: kohteella on rakennus taajaman aluerajauksen sisällä ja kohteen rakennusten huoneistomäärä on yhteensä vähintään 5.',
         'Biojätteen tyhjennysväli on enintään 4 viikkoa (1-4 vk).'),
    (52, 'Biojätteen erilliskeräysalueen kohteet: kohteella on rakennus vähintään 10 000 asukkaan taajamassa ja kohteen rakennusten huoneistomäärä on yhteensä enintään 4.',
         'Kohteelta puuttuu voimassa oleva biojätesopimus eikä sillä ole voimassa olevaa kompostointi-ilmoitusta.'),
    (53, 'Biojätteen erilliskeräysalueen kohteet: kohteella on rakennus vähintään 10 000 asukkaan taajamassa ja kohteen rakennusten huoneistomäärä on yhteensä enintään 4.',
         'Biojätteen tyhjennysväli on 0 tai yli 4 viikkoa.'),
    (54, 'Biojätteen erilliskeräysalueen kohteet: kohteella on rakennus vähintään 10 000 asukkaan taajamassa ja kohteen rakennusten huoneistomäärä on yhteensä enintään 4.',
         'Biojätteen tyhjennysväli on enintään 4 viikkoa (1-4 vk).'),
    (55, 'Biojätteen erilliskeräysalueen kohteet: kohteella on rakennus vähintään 10 000 asukkaan taajamassa ja kohteen rakennusten huoneistomäärä on yhteensä enintään 4.',
         'Kohteella on voimassa oleva kompostointi-ilmoitus.')
) AS v(id, saannon_selite, tayttymissaannon_selite)
WHERE vm.id = v.id;
